# Generated by Django 5.2 on 2025-04-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
